### ISSUE TITLE
Invalid ELF Header

### ISSUE THREAD

**Issue by ahmedHusseinF** [ZiNai/check-email-exists#3]
just ran the npm install and it fails with invalid elf header while running the example.

```js
Error: /home/playing/mails/node_modules/check-email-exists/native/index.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ahmed/playing/mails/node_modules/check-email-exists/lib/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

```

**Comment by ZiNai** [comment]
Whether your OS is windows, I updated the rust and built the repo in travis, but windows always fails. If you get a new version to try again
